### ISSUE TITLE
Build Number

### ISSUE THREAD

**Issue by arthurbenemann** [diydrones/ardupilot#1104]
Currently there isn't a good way to check via the GCS software the Ardupilot software on whatever board we are connected to.

Since we don't have a way right now to save a string as a parameter a possible fix would be to have a Version Code similar to what Android Apps use. Here is the description:

> android:versionCode — An integer value that represents the version of the application code, relative to other versions.
> The value is an integer so that other applications can programmatically evaluate it, for example to check an upgrade or downgrade relationship. You can set the value to any integer you want, however you should make sure that each successive release of your application uses a greater value. The system does not enforce this behavior, but increasing the value with successive releases is normative.
> Typically, you would release the first version of your application with versionCode set to 1, then monotonically increase the value with each release, regardless whether the release constitutes a major or minor release. This means that the android:versionCode value does not necessarily have a strong resemblance to the application release version that is visible to the user (see android:versionName, below). Applications and publishing services should not display this version value to users.

Reference: http://developer.android.com/tools/publishing/versioning.html

This could be embedded as a Read-only parameter, modifiable only by changing the source code. Changes to GCS software are minimal, but the benefits are enormous. That way we can easily enable/disable feature based on a simple integer comparison.

**Comment by magicrub** [comment]
what's the status on this?

**Comment by rmackay9** [comment]
I'm closing this because AC3.3 supports the AUTOPILOT_VERSION message.
http://mavlink.org/messages/common#AUTOPILOT_VERSION

We are not properly filling in the capabilities bitmask of that message but that's a separate request (although it's raised above).  I think we need some specific cases to appear where the GCS developers care whether a feature is implemented or not and then we will fill that in.  So... closing this general issue, let's raise a new more specific one if anyone can think of a case where we need to fill in the capabilities bits.
