### ISSUE TITLE
Copter: allow battery failsafe to become unset after 10seconds of good voltage

### ISSUE THREAD

**Issue by Pomaroli** [diydrones/ardupilot#1327]
Hello @ll,
i have an F550 hexacopter which is controlled by pixhawk 3.1.5.
The copter  has also the other 3DR stuff like Telemtry, GPS and so on.
I'm using this copter for Acrobatic Flying and having a lot of fun.

i've noticed an issue which i try to explain as follows : 
with my hexa I'm starting from the ground with a fully charged 4S battery and i'm accelerating to maximum to gain high usually to about 150-200meters the hexa needs about 5-6 seconds. During this process of gaining high the battery seems to lose voltage for a small amount of time which is enough to trigger the Failsafe. The LED Starts to flash yellow and the Buzzer is buzzering around. After altitude is reached and the acceleration is stopped by pilot the batttery returns to the "normal" voltage and will remain there, the buzzer stops buzzering but the LED is still flashing yellow. Should it not return to normal state green or blue because the voltage turns back to ok ?
After Flight time of about 5 minutes the battery is empty and it reaches the Failsafe Voltage for "Real" but the buzzer is not buzzering to warn the pilot, should it not restart buzzering ?

**Comment by rmackay9** [comment]
I've investigated this and I see what you're saying.

So there are two issues raised above.  The first is that in AC3.1.5 the buzzer stopped buzzing once the voltage returned to normal.  This is serious because the pilot could be unaware that a battery failsafe has happened.  This is fixed in AC3.3 (and maybe AC3.2.1) - once the buzzer starts it will keep going until the vehicle is disarmed.

The second issue is a request to allow a recovery from a battery failsafe if the voltage return to normal for a decent period of time (maybe 10 seconds).  This is not done in AC3.3, once it enters the battery failsafe it stays in this state until the battery is disconnected/reconnected.  This is not really a safety issue -- it's more of an enhancement request to allow the pilot to keep flying after a (temporary) low voltage situation has occurred.
I've changed the title to clarify this issue is about this enhancement request.

Also AC3.3 includes an additional arming check of the battery voltage to ensure the pilot doesn't take off with a dead battery.

I'm also pushing this item to AC3.4 because we're simply out of time for AC3.3.

**Comment by Pomaroli** [comment]
Yes i can confirm, the actual beta i've tested AC 3.3 rc7, is working as described on first issue and how i would expect it should. So were fine.

On Second described issue, i'm quite unsure this is a proper solution. If this would happen to me i would expect something is wrong with the battery and would prefer the alarm.

**Comment by rmackay9** [comment]
Pomaroli,
Ok, if you're not interested in the recovery from the battery failsafe?  If that's the case, maybe I'll close this issue?

**Comment by Pomaroli** [comment]
Randy, on my opinion on the newest beta it's like it should be. From my point of view feel free to close. If there is the issue that battery voltage is braking down shortly so that fs is triggered, this is a several issue with the battery healthy, discharge rate or at least on the cable current carrying capacity. (AWG)

**Comment by rmackay9** [comment]
Great, totally agree.  closing!
