### ISSUE TITLE
Copter: return to me

### ISSUE THREAD

**Issue by TerryPts** [diydrones/ardupilot#1621]
The new DJI Inspire has, what they call, dynamic relocate for RTL. This would be great for boat flying and I'm guessing it would be fairly easy to implement in Arducopter using the followme info. The launch  location could be constantly updated by the ground station location.

**Comment by rmackay9** [comment]
The arducopter side of this is done now in a somewhat basic way at least.  The home position can be set from the GCS and that will be used as the RTL location.

Issue raised for DroidPlanner to implement the GCS side: https://github.com/DroidPlanner/droidplanner/issues/1397

**Comment by TerryPts** [comment]
Thank you Randy, 
I'm excited to see 3.3. Would it make sense to call it 4.0 if it is the first version to be Pixhawk only?

**Comment by PaulHam211** [comment]
I know this issue is closed, but i know its something that is being worked on and i would like to add my 2 cents.

Can there be some sort of checking that makes sure your dynamic home point isnt too far away from the takepoff point? I know it wont work for everyone so perhaps a param to turn on and off. 

Reason i ask if because i saw a DJI Inspire fly away on the past weekend, The guy tried to return to Inspire to the position of the GCS, for some reason the GCS gps was showing 3km away, in the middle of a motorway!  By the time the guy realised what was happening the inspire was out of range of the control and the inspire was never seen again, We have no idea where it ended up.

If the GCS could have worked out that it would have been impossible for the guy to turn on the inspire, take off then travel 3km with the controller within this small amount of time,  then im sure this flyaway would have been avoided.

I do realise that this is completely pilot error, he should have checked if all GPS were locked correctly but it might be something to think about.
