### ISSUE TITLE
Copter:Failed to initialize optflow

### ISSUE THREAD

**Issue by figwig** [diydrones/ardupilot#1637]
Does this firmware even support optical flow? Been trying for around total 8 hours now and it doesn't initialize.

**Comment by Craig3DRobotics** [comment]
Optical flow is supported in Plane and in Copter Master.

**Comment by rmackay9** [comment]
@figwig, are you trying to use the PX4Flow sensor or the older mouse sensor?
The two are shown on this page: http://copter.ardupilot.com/wiki/opticalflow-landingpage/

**Comment by figwig** [comment]
The older mouse sensor, I've used that page and followed each step very
closely, and still no help!

**Comment by rmackay9** [comment]
@figwig, it should work although I can't remember anyone testing it as part of the AC3.2 testing.  To be honest, the sensor never really lived up to expectations mostly because we didn't have a really good way to integrate the sensor data.  Now with the EKF on the Pixhawk, the higher grade PX4Flow sensor seems to be working much better than the mouse sensor ever did.  It's still just in testing though and won't be ready for widespread use until AC3.3.  And AC3.3 won't run on the APM2 which is what you must have.
Sorry I can't be of more help.

**Comment by figwig** [comment]
Okay, cheers for the help. I'll save up for a pixhawk AF some point then.
Thanks
