### ISSUE TITLE
Copter: Erratic Yaw Behavior With Spline Waypoints

### ISSUE THREAD

**Issue by TheBuzzAbove** [diydrones/ardupilot#1638]
Sometimes the drone yaws sharply to left, right, or both when using spline waypoints. I've linked to a short comparison video that shows the same mission with spline waypoints on the left and normal waypoints on the right. As far as I can tell, it happens with and without a ROI. Sometimes, it's veers off way further than in the comparison video. It's like it wants to point to 180 degrees or 0 degrees, then corrects itself.
http://youtu.be/PTwXBoFAxxY

**Comment by mmaunder** [comment]
I'm seeing the same issue. ROI gets confused when using spline waypoints. Link to my log:

https://drive.google.com/file/d/0B6ZsF5nou253R3I2ZDl0YXI3YWM/view?usp=sharing

Here is the first part of the mission commands that are relevant:

http://i.imgur.com/Bdp5CR2.png

After spline waypoint 7 in the log it immediately sets the ROI to be the very first ROI in the mission. There is no command between 7 and 8 to change ROI. Also my understanding is pre 3.2 the behaviour was to have the ROI only last until the next waypoint and then reset. That's not what's happening here because the previous ROI is set at step 5, then there's a spline, another spline and then it reverts to the first ROI. 

To save you some time, spline waypoint 7 in the binary log is at line 16279 and then the ROI command is at 16280. Both occur at 116961ms.

I haven't tried any workarounds yet but I suspect reverting to the 3.1 behavior of constantly re-specifying your region of interest between waypoints is going to be the fix until this is fixed. 

Thanks - and thanks for a wonderful piece of software!!!! 

~Mark.

**Comment by rmackay9** [comment]
@mmaunder,
Thanks for the report.  I've tentatively put this on the list to sort out for AC3.3.

**Comment by mmaunder** [comment]
Thanks Randy, let me know what I can do to help. Happy to load beta firmware (and I'm aware of the risks). I'm also a dev although my C skills are a little rusty - mostly work with loosely typed langs these days. Weather just improved here in Colorado so I'll do another few flights later today to try and repro the issue again.

**Comment by mmaunder** [comment]
OK I think I made some progress today in figuring this out. So I did another mission that's similar to the last one that caused the ROI problem. Had the same symptoms. I set ROI before takeoff, leave the ground and head towards a target in the distance and as expected the camera is pointing backwards at my initial ROI. 

I then get to the destination where I want to do a circle around something interesting so I set the ROI to the interesting thing and start my circle. A couple of waypoints into the circle, it points the camera back at the original ROI. 

Check out this filtered log: 

http://i.imgur.com/9YCpY99.png

Notice the CId 201 command entries which is the ROI. You can see it keeps rerunning the ROI between waypoints en-route to the destination. So I guess 3.2's fix for maintaining ROI across waypoints was to just run the ROI command again between waypoints. 

Notice the latitude of each ROI (CId 201) is 39.37664 so you can tell which ROI it is. 

Then at line 42615 it gets interesting. It sets the initial ROI and then the very next command sets the new ROI. 

Then check out line 58668 where we have the root of the evil. It sets the ROI back to 39.37664 and bam! The camera is pointing out into space instead of at my interesting ROI. 

It continues to set that ROI until end of mission. 

So it looks like the bug is that the 3.2 fix which causes the ROI to persist between waypoints also causes that ROI to get re-executed even after you specify a new ROI. 

I'm attaching the relevant portion of the flight plan so you can see where I'm using spline's, regular waypoints and ROI's. 

http://i.imgur.com/mObfe4y.png

Full log of this mission is linked. FYI, I had another rather serious problem with this mission in that the aircraft progressively lost altitude when returning home from 120 meters down to 20 meters and all waypoints were set at 120 meters altitude. But I may file a separate bug for that if I figure out it wasn't something I did. 

https://drive.google.com/file/d/0B6ZsF5nou253SDFyVGQ2S1lyY0k/view?usp=sharing

**Comment by rmackay9** [comment]
@mmaunder, Sorry for the delay in looking at this.  Were you using DroidPlanner or Tower maybe to create the mission?  My guess is that the ground station was trying to be helpful and created all those extra ROI commands.  There was an issue in AC3.1.5 (I think) where ROI would not persist across waypoints so maybe the Tower/DroidPlanner guys tried to create a workaround that went wrong in this case?

**Comment by rmackay9** [comment]
@mmaunder, I looked into this further and it is indeed a bug in ardupilot's AP_Mission library!  It's not a problem with DroidPlanner/Tower.
The fix is in master now and will go out with AC3.3.  https://github.com/diydrones/ardupilot/commit/766ccea3be11c7b38d5f0a09f0db7ac836af21d5

Thanks again for the report and detailed logs.
