### ISSUE TITLE
Copter, Mission: Change_Speed only works once if using EKF.

### ISSUE THREAD

**Issue by AndKe** [diydrones/ardupilot#1713]
To reproduce: 
create a mission like this:

Change_Speed 2m/s 
Waypoint 1  
Change_Speed 5m/s 
Waypoint 2

2m/s will be set, never 5m/s

Is this by design ? - why ?

**Comment by AndKe** [comment]
Here's a very much more to-the-point log:  http://www.droneshare.com/mission/50051
Mission plan was simple: 
1: set speed 2m/s
2: waypoint
3:set speed 8m/s
4 waypoint

The second speed change never happened.

**Comment by AndKe** [comment]
I think I've found the problem - will verify, then you can expect a pull request

**Comment by rmackay9** [comment]
@AndKe, great!

**Comment by AndKe** [comment]
I must admit that the wp navigation /speed code is hard to understand, apparently I'm a bit in over my head here :)
I thought the problem was the conditional statement in void AC_PosControl::set_speed_xy  - that set variable and recalculated leash only if speed was reduced, but that did not solve the problem.
Currently trying to see if something the leash can be disabled, or somehow to blame.

**Comment by AndKe** [comment]
Ok. I failed to find the bug.
After very much testing of modified firmware, I narrowed it down to this as a first step:

It's the speed *increase* , and increas only - that is delayed beyond expected WP, not "not set" as I claimed in the subject.

An speed increase from 8m/s to 12m/s, is happening one waypoint too late:  http://www.droneshare.com/mission/53571
Please observe that GPS.Spd increases one WP too late (plot CMD.CId and CMD.Prm2 too)
Similar test with speed reduction, kicks in instantly.

Now please look at test 120 , same commands.  - works perfectly !  - AHRS_EKF_USE is 0. 

Does this narrow it down so much that you can figure it out ?

**Comment by lakeroe** [comment]
I think I observed a similar thing.
I did a small testmission including several DO_CHANGE_SPEED commands and it did not work as axpected.
It seems like the command is ignored sometimes.

The log-file, mission and parameters are for download here:
http://www.adrive.com/public/VXJDQd/do-change-speed.zip

**Comment by rmackay9** [comment]
Ok, I've reproduced and fixed this problem.  The fix will go out with AC3.3-rc5 this weekend.
https://github.com/diydrones/ardupilot/commit/d1808c645d041f4d0729a5a14409236aea7a1744

In case anyone is interested the issue was that the pos-controller's leash length wasn't being immediately updated after a do-set-speed change.  It was updated very soon after but because it wasn't immediate the waypoint controller was grabbing a stale value and using it.  This meant that even though the waypoint controller new it could go at full speed it wouldn't let the litle target position that the vehicle is following get far enough ahead for the vehicle to reach top speed.

There's a bit of clean-up that we should do to remove some flags in the position controller, flags that were added for the APM2 when we needed to be really careful about CPU useage.

**Comment by AndKe** [comment]
Thank you for fixing, and a great explanation. 
I'll take a look at the code later, I suspect the bug https://github.com/diydrones/ardupilot/issues/2227 may be related, not to EKF, but generally to something not being updated properly.  And your fix can , maybe, help finding solution to the other one..

**Comment by rmackay9** [comment]
@AndKe, I don't think the plane issue can be related to this issue because we don't (yet) share any navigation or even attitude control code with plane (estimation is shared but not control).  Sorry I can't be of more help on that.

**Comment by AndKe** [comment]
I meant generally similar problem of the same nature (a missing call to an recalculation)  - but It was not that.  Thanks.
