### ISSUE TITLE
apm copter: throttle failsafe 

### ISSUE THREAD

**Issue by matrixFLYER** [diydrones/ardupilot#1937]
Hi. In the same days happens to me to hit solid things two times with my quadcopter. Both time at less then 50cm of height from the arming point.
The first time i was flying in stabilize mode: as soon as i hit something the copter disarmed itself : excellent. (Outdoor gps 3d lock)
The second time i was testing throttle failsafe set to enable always land. While landing (indoor no gps 3D lock)  the copter hitted something and it didn't disarmed. I was not able to disarm it manually. It stopped only after 1 minute or more.

**Comment by rmackay9** [comment]
This is more of a support question so should go into the APM Forum instead of here on the issues list.  Sorry to be strict but if we're not the to-do list just turns into a support forum.

The vehicle can be disarmed with the sticks when it's in stabilize or acro mode OR in other modes as long as the vehicle thinks it's landed.  If it's flapping about on the ground it won't think it's landed and thus won't let you disarm.
