### ISSUE TITLE
Plane: throttle can unsuppress when we get GPS lock

### ISSUE THREAD

**Issue by tridge** [diydrones/ardupilot#1976]
if in RTL on ground and get late GPS lock throttle in plane can unsuppress

**Comment by magicrub** [comment]
I have experienced a throttle unsupressing itself while handling the aircraft during a bungee TAKEOFF which is quite dangerous but was never able to reliably duplicate it. Even happened once while sitting on my bench - would be in line with a GPS loss. I'll try testing /w intentional GPS loss and report back.

**Comment by magicrub** [comment]
@tridge you had mentioned on mumble how you may be able to duplicate bug's behavior in SITL but my memory is failing me, what was that procedure?

**Comment by magicrub** [comment]
while looking over the code I notice that if you're armed and in a TAKEOFF waypoint, such as a bungee launch, the throttle suppress can come off due to an altitude or gps glitch. This is specific to the TAKEOFF wp, and a little different than what you're observing, but it would probably be a good idea to change suppress_throttle()
from:
    if (control_mode==AUTO && 
        auto_state.takeoff_complete == false &&
        auto_takeoff_check()) {
            // we're in auto takeoff
            throttle_suppressed = false;
            return false;
    }

to:
    if ((control_mode==AUTO) && (auto_state.takeoff_complete == false)) {
        if (auto_takeoff_check()) {
            // we're in auto takeoff
            throttle_suppressed = false;
        }
        return false;
    }


That way if we're ever in a takeoff situation where people are handling the aircraft while armed we should ignore any GPS/altitude glitches regardless of how they happened. When in takeoff, the only way to unsuppress is to satisfy auto_takeoff_check() which has timers and such.

**Comment by magicrub** [comment]
This may be fixed, please confirm @tridge

**Comment by magicrub** [comment]
confirmed, this is now in master.
