### ISSUE TITLE
Waypoints on SD card

### ISSUE THREAD

**Issue by VladimirP1** [diydrones/ardupilot#1999]
Why does Pixhawk need so many flash memories?
I mean you could store waypoints on SD card also. (Can even leave the same memory layout, only increase size and put to binary file in SD card)

It will be possible to fly in loiter, then "replay" the flight (For example load waypoints to it, generated from tlogs)

**Comment by rmackay9** [comment]
SD cards are not that reliable actually because the board can be powered down at any time which can corrupt the FAT file system.

Copter has the ability to store the current location as a waypoint using a ch7/ch8 switch although the recording of the points is done manually (it doesn't automatically record them as the vehicle flies).

May this is more like a question that could go on drones-discuss@googlegroups.com?

**Comment by VladimirP1** [comment]
Does NuttX have partitioning support?

**Comment by VladimirP1** [comment]
Terrain following also writes to SD card.

**Comment by magicrub** [comment]
What is the status of this issue?

**Comment by rmackay9** [comment]
I think we can close this.  We support up to 700+ waypoints on Pixhawk now so not sure how much we would really gain by moving to a less reliable storage
