### ISSUE TITLE
Pixhawk and EMAX 4in1 ESC issue

### ISSUE THREAD

**Issue by tonypascal** [diydrones/ardupilot#2033]
Hello,
There seem to be a big problem with the Pixhawk and 4in1 ESC as reported here:
http://ardupilot.com/forum/viewtopic.php?f=21&t=5784&start=30
How could we deal with this problem, we are a handful of people not being able to fly our drones because of that...
Thank
Tony

**Comment by R-Lefebvre** [comment]
This seems like a hardware issue to me, nothing we can do in software. As a couple people have indicated, the input impedence on the Emax ESC is not high enough, so the PWM pulse amplitude seen by the Emax ESC is not high enough. This is made worse on the Pixhawk , since it's driving the PWM at 3.3V instead of 5V as the APM2.5 does.

This is not the first time that an ESC has had this problem, there are a number of them out there that have it. Unfortunately, if this is the problem, there is really nothing we can do in software.

I suspect the fact that it sort of works maybe kind of sometimes, is an indication that you are on the ragged edge, and the PWM pulse is going over 3.0V, but takes a bit of time to get there, thus there's this off-set seen between min throttle.

Now, I have to ask, do you have a ground wire between the ESC and the Pixhawk?

This is the part that's not totally clear to me at this point.

I do not think the kinda/sorta/sometimes it works situation, is an indication that there is a problem with the software, as if there were, then all ESC's would have the same problem, not just a few.

**Comment by CraigElder** [comment]
Hello all,

I took the problem the other way. I asked EMAX why it doesn't work. I wrote them an email and here is their answer:

"The current 4 in 1 ESC 25A doesn't support Pixhawk, we had noticed that and are currently modifying the firmware and doing test so that the new firmware will be compatible with Pixhawk flight controller. We will finish test in around a week. I will keep you posted about it."

So, hopefully, we should have some news next week.

Tony

**Comment by alduxvm** [comment]
Any update on this subject? or just the official response is "don't use EMAX with pixhawk"?

**Comment by nickn7** [comment]
Ditto! I liked to use a Emax 4in1 on a quad but am
stuck using a Naza-Lite(V2) instead. Wish Emax would
get with the program. Won't buy another Emax ESC.

On Sun, Jul 19, 2015 at 8:02 AM, Aldo Vargas <notifications@github.com>
wrote:

> Any update on this subject? or just the official response is "don't use
> EMAX with pixhawk"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot/issues/2033#issuecomment-122670014>
> .
>



-- 
*I plan on livi**ng forever. *

 *  So far, so Good!*
   *Cheers, **☆*NickN**

**Comment by rmackay9** [comment]
It's tough for me at least to fix this very low level behaviour on the pixhawk.  The pins are pulled high when the pixhawk starts up rather than low like they did on the APM.

**Comment by alduxvm** [comment]
Everyone that is still interested in the EMAX / Pixhawk dilema... Developers were correct. It was a ESC hardware issue. 

Unsolder a remove the two resistors marked in the picture and the ESC will work with pixhawk.

![12a](https://cloud.githubusercontent.com/assets/8823379/8927757/912a876c-3511-11e5-9f2c-ce0c5f0857af.jpg)

**Comment by rmackay9** [comment]
Well, that is great news that the issue is understood.

**Comment by garethbradley** [comment]
Hi,
Anyone know how to modify a EMAX BLHeli 20A ESC to work with the Pixhawk? Looks different to the above image.

![img_20150912_102417-01](https://cloud.githubusercontent.com/assets/450835/9830913/0caeb3ea-5939-11e5-90d3-95709704e2bd.jpeg)

Thanks!

**Comment by alduxvm** [comment]
My suggestion will be to contact emax support... they might take some time in answering you, but they will tell you exactly which components to remove.

**Comment by garethbradley** [comment]
I asked the question - no response yet...

**Comment by drfailov** [comment]
Just if somebody has ESC wiht the same layout as mine, remove these two components to fix compatibility issues:
![20161106_130500](https://cloud.githubusercontent.com/assets/18188339/20042252/3efcdccc-a47f-11e6-8a9e-e6a3f40d7970.jpg)

I don't know what exactly model is it, but found this solution by testing board pins.
Now it works fine.

**Comment by magicrub** [comment]
what do those two caps do? What signals are on them?

**Comment by magicrub** [comment]
This may be a good thing to add to the wiki. Any volunteers?

**Comment by drfailov** [comment]
As mentioned in some thread in Diydrones, ESC don't work because it stuck in the bootloader while booting up. The reason of that can be different output signal from Pixhawk than the APM. 
So, in my opinion this 2 elements do some filtering to the signal, which already did in Pixhawk.

**Comment by Steadyspike** [comment]
I have same problem with Emax Lightning 30A BLHeli and Pixhawk. Does someone know which components should I replace/modify? Find attached a photo.
![emax_b](https://user-images.githubusercontent.com/24420713/31050605-940ecbf8-a64f-11e7-89cb-e399c5560e87.jpg)
![emax_a](https://user-images.githubusercontent.com/24420713/31050606-9411f454-a64f-11e7-978b-9904cd50324c.jpg)

**Comment by drfailov** [comment]
Steadyspike, try to discover resistors between signal and ground and dismount it. I did my modification in same way.
Notice, that after that modification ESC will act randomly when not connected to FC.

**Comment by Steadyspike** [comment]
It's no so easy... anyone with the same problem has fixed it?
