### ISSUE TITLE
How to include arduino core in include path??? 

### ISSUE THREAD

**Issue by anisjamil** [diydrones/ardupilot#2113]
Hello,
   I'm using arduino 1.0.3 for arduplane 3.1.1. Once I compile the code I can't access the arduino core liberaries and it displays me the following message.

Building for ArduPilot Mega 2.x
Excluding arduino core from include paths

  Anyone kindly tell me that is there any specific way to include these files. I have written the command #include <Arduino.h>

**Comment by rmackay9** [comment]
As part of the development of ardupilot we had to drop the native Arduino libraries both so that we could add support for other boards (like Pixhawk) but also because we bumped into limitations with the arduino libraries.
I'm not sure that it's even possible to include the native arduino libraries, it's certainly not something that we support.  It's possible there may be a way, and perhaps asking on drones-discuss@googlegroups.com may help you find someone who knows the answer.
