### ISSUE TITLE
Copter + Alexmos : pixhawk crash on every reboot when not setting serial protocol to Alexmos value.

### ISSUE THREAD

**Issue by MaxxUAV** [diydrones/ardupilot#2371]
Hello, guys I just experimented a bug on my pixhawk in revs 3.3rc1 and rc5. 
I discovered that setting parameter "_TYPE" to Alexmos value without changing the serial4 parameters  ("4_PROTOCOL" and "4_BAUD") to alexmos protocol will crash the pixhawk on every reboot forcing me to reflash older firmware or change the parameters on the files AP_MOUNT and AP_Serial_Manager. The serial4_protocol was by default on the "gps_protocol" value.

Hope this will help beta-testers and thanks for good development in this library, this works really fine !

**Comment by rmackay9** [comment]
Thanks very much for the report!
Fixed with this commit and will go out with AC3.3-rc6: https://github.com/diydrones/ardupilot/commit/b8e3fe8f262118b88693ef474feccc750ef3f14c

I don't think this driver has been tested very much so I'd really like to hear how i goes so can you post your testing results either to the AC3.3 beta testing thread or drones-discuss@googlegroups.com?

Thanks again.
