### ISSUE TITLE
EKF: calculate wind.z

### ISSUE THREAD

**Issue by magicrub** [diydrones/ardupilot#2718]
Current EKF does not calculate the z axis and is noted as so in the source:
    wind.x = state.wind_vel.x;
    wind.y = state.wind_vel.y;
    wind.z = 0.0f; // currently don't estimate this

Adding this would help pave a path to more advanced auto-path planning improvements, namely gliders auto-thermal hunting.

**Comment by magicrub** [comment]
Of note, looks like DCM *does* populate the z axis so the EKF is a regression there.

**Comment by priseborough** [comment]
In practice this was not a regression. The Z component is very poorly observable using the DCM method given it assumes zero angle of attack and produces offsets that make it unsuitable for path planning, thermal hunting, etc.

To do it properly would require adding some vehicle flight dynamics properties into the estimator, so that the relationship between angle of attack and lift is included. This is best done outside the EKF as it is platform specific.

-Paul

**Comment by magicrub** [comment]
awwww, what a let down. So what you're saying is it's not implemented yet because it's harder than I think it is to implement it? Dang!

**Comment by magicrub** [comment]
Will not implement, no benefit
