### ISSUE TITLE
Time delay when switching flight mode using Mavlink.

### ISSUE THREAD

**Issue by migvel** [diydrones/ardupilot#2773]
I'm experimenting with obstacle detection using a companion computer, when the object is detected(by a sonar) the companion sends a mavlink_msg_set_mode to the Pixhawk(with Arducopter on top).

The Quadcopter is reacting properly but there is a delay(around 600ms seconds) in between when the message is sent and when the UAV actually reacts, that takes a bit longer to stop the copter and therefore gets closer to the obstacle than expected.

Right now when the object is detected the UAV switches to RTL mode from Loiter. Is that behaviour(timing wise) normal or expected?

**Comment by rmackay9** [comment]
No, that's not expected.  Are you sure it's not a delay in the serial connection from the companion computer to the Pixhawk?  Perhaps there's a buffer on the companion computer side that's filling up?

I'm going to close this issue because it's not clear yet whether it's actually an ardupilot issue (unlikely), a hardware or a companion computer issue.

It might be best to discuss this on drones-discuss@googlegroups.com.

**Comment by migvel** [comment]
After checking more I found that the source of delay is not in the Ardupilot software.

Thanks.

**Comment by rmackay9** [comment]
@migvel, ah, excellent.  thanks for the follow up.
