### ISSUE TITLE
Guided mode turn into RTL mode unexpectedly

### ISSUE THREAD

**Issue by PenguinCheng** [diydrones/ardupilot#2880]
Hello,
I am working on a job that uses an odroid-u3 connected with pixhawk to control my quadrotor. After i ran my code for a while, the pixhawk turned into RTL mode. However, i didn't write the command to turn into RTL mode. In my code, i give velocities every one second and the function is ‘send_ned_velocity()’(vehicle.message_factory.set_position_target_local_ned_encode()). 
I don't why it ran into RTL mode unexpectedly. And in what situation, the pixhawk will run into RTL mode?
could someone help, thank you in advance!

**Comment by killerlayup** [comment]
I have the same issue! It really confused me..... T T

**Comment by magicrub** [comment]
Have you checked your FS_* params?

**Comment by rmackay9** [comment]
This is really a support and/or developer question so I'll close it here.  Sorry to be annoying but otherwise the github issues list becomes a support forum.

If we consider this a developer question, then posting it on drones-discuss is ok.  If it's a Copter-3.3-rc that you're working with, posting this on the Copter-3.3 beta testing thread is also a-ok.

**Comment by PenguinCheng** [comment]
I am going to check my FS_* params, to see if it's the problem. Thank you for your reply.

**Comment by PenguinCheng** [comment]
Thank you for your advice!@rmackay9
