### ISSUE TITLE
Copter: IR Lock cause compass not healthy prearm check failure.

### ISSUE THREAD

**Issue by derekxm** [diydrones/ardupilot#2955]
When IR-Lock is plugged in to I2C port of Pixhawk along with 3DR uBlox external compass, ArduCopter raises "Compass not healthy" warning and prevent vehicle from being armed. The prearm check goes away if IR-Lock is unplugged. Attached is my parameter file.

My parameter file is here
https://drive.google.com/file/d/0BxJyeq3gZcUlaWZVQXEzNTZHOUU/view?usp=sharing

**Comment by rmackay9** [comment]
@derekxm, this is unlikely to be a software issue.  The more likely causes are:
1. the I2C cable from the IRLock to the Pixhawk has been incorrectly wired (i.e. wires are swapped around or something similar).
2. the IRLock's I2C address is conflicting with the compass
3. the Pixhawk is not able to power the IRLock sensor and the compass.

I've successfully used the IRLock with an external GPS/compass on my IRIS.
You've followed the wiki page carefully regarding the setup?
http://copter.ardupilot.com/wiki/precision-landing-with-irlock/

To be honest, I think this is more of a support issue than a firmware issue so I'll close this but I'll keep monitoring for replies.  You can also email drones-discuss@googlegroups.com.  In your subject line, please put something like, "problems trying out precision landing with IRLock" or something similar so it's not rejected because it's a support issue.
