### ISSUE TITLE
Safety feature: change external compass behavior

### ISSUE THREAD

**Issue by msk7-ripe** [diydrones/ardupilot#2963]
Now when AP detects ext compass it switches it to be first one. In case of wiring defect AP may apply wrong offsets/orientation to internal compass as ext wouldn't be detected. I think this is not good.

What I suggest: not to switch compass numbers on ext compass detection, but set COMPASS_PRIMARY param. In this case all offsets and tuning data would be tied to specific device.
Also AP should check on startup if any calibration data are nonzero for non-existing device and raise error indicating previously tuned compass is no more present.

**Comment by rmackay9** [comment]
Well thought out report.
..but Copter 3.2.1 (and higher) check that the device id of the detected compass matches the device used when the compass was calibrated so we can be sure that the offsets are for that device.  If they don't match a pre-arm check "compass not calibrated" appears.
I'm going to close this issue because with these catches in place I think it's safe.
