### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by jackson-xi** [diydrones/ardupilot#3767]
![m3112 2z f 1 f ke_ h 5](https://cloud.githubusercontent.com/assets/16152270/13880073/888328a6-ed55-11e5-9480-283f366a40d4.png)
Hi, everyone.Actually, I can't download the APM3.2.1 code successfully into APM2.6. I promiss I do anything accorading to http://dev.ardupilot.com/wiki/building-ardupilot-with-arduino-windows/. But the APM board can get the right appearance when I have downloaded the code. I will appreciate anyting.

**Comment by magicrub** [comment]
I'be never built for arduino but it is considered legacy and has not been
supported by the main master branch for a while. You must use the
master-AVR branch.

**Comment by rmackay9** [comment]
I think it should work with master if you go back to the ArduCopter-3.2.1 tag (or whatever it's called).  I think what's happening is that after compiling it's over the AVR's flash size limit.  It was really barely fitting and the code size can change a bit depending upon the compiler.  So if you use a slightly older compiler than we did it likely won't fit.
I'm going to close this because we don't support the AVR anymore, sorry!
