### ISSUE TITLE
Display Ublox Jamming value in mission planner

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#640]
The Ublox does provide a jamming parameter which generally returns a number between 0 ~ 6 to indicate the level of jamming.  0 ~ 2 = minimal jamming.  6 = completely jammed.
Making this parameter available might help some users determine they have equipment on their vehicles that is interfering with the GPS so they can correct it.

**Comment by rmackay9** [comment]
In AC3.3 we're still not sending this to the GCS but it is being logged to the dataflash in the UBX1 message.

**Comment by WickedShell** [comment]
According to the data sheet the jamInd is scalled 0-255 (on both the 6 and the 8 at least) and looking through my logs that is still the case. Are you sure about the 0-6? Or is that simply related to having not seen much above a 6 in people's logs?

The jammingState portion of flags is probably more useful in someways, it returns one of the following
  -No signficant jamming
  -Warning - interference visible but fix okay
  -Interference visible and no fix

Anyways the jamInd (what is in the UBX1 message) is dependent upon having run the receiver in an unjammed environment to determine what the base noise level is expected to be. (IE it is expected to fluctuate depending on application/installation).

jamState is potentially useful as well since it is computed independently of jamInd, is easy to interpret and is responsible for looking at both broadband and continuous wave interference. (jamInd is CW only)

**Comment by rmackay9** [comment]
@WickedShell, when I first created this issue I didn't have much experience with the jaming id so as you suspect, I just hadn't seen many numbers above 6.

**Comment by WickedShell** [comment]
Closing this in favor of moving this type of logic to the GPS glitch detectors and failsafe handling on the GPS side. Part of the problem here is that the jamming ids that should trigger something are different for every vehicle setup and without a user deciding what this should be set to on their hardware we can't use these automatically.

The info is available in DF logs btw.
