### ISSUE TITLE
Copter: New manual (Non-GPS) flight mode for Tablet only flight

### ISSUE THREAD

**Issue by grmccray** [diydrones/ardupilot#668]
In tablet flying mode, the virtual sticks are suboptimal and "clumsy" to use compared to physical sticks, also there is an approximately 1/2 second delay in the 3DR telemeteric link.
For these reasons I am proposing that a new inertially stabilized manual flight mode incorporating Altitude Hold be developed for manual (non-GPS) flight for copters using a tablet only interface.
It would work essentially like stabilize with altitude hold on but it would slow responses down and use inertial stabilization to maintain smooth flight.
This would not be a high performance flight mode rather a low performance high integrity inertially stabilized flight mode designed to permit safe manual control and especially to allow for manual recovery in the event of GPS signal failure for whatever reason.

**Comment by R-Lefebvre** [comment]
Does the new ATC_Accel parameters solve this problem by slowing down the responsiveness of the copter?

**Comment by rmackay9** [comment]
@R-Lefebvre, I'm not sure.  I actually don't think we can do the "inertially stabilized" flight mode suggested above without a GPS or optical flow.  Without an external reference for velocity or position there's no good way to counteract the drift in the accelerometers.

**Comment by R-Lefebvre** [comment]
Yes, that's right.  Alt-Hold can have non-GPS position control, only because we have barometer sensor which can be used to cancel drift of the inertial system.  But there is no equivalent for the baro in the X and Y directions.  There's just nothing we can do here. 

We could do linear acceleration control, but that's it.  And given linear acceleration is so closely tied to lean angle, and we already have lean-angle control (Stabilize) I don't really see the point in developing an acceleration-controlled flight mode.  

Another point, is that optical flow will allow non-GPS position control.  And it seems that will be working in the near future.

I recommend closing this issue.
