### ISSUE TITLE
Copter: GCS failsafe should trigger if in Guided mode and loss of telemetry

### ISSUE THREAD

**Issue by rmackay9** [diydrones/ardupilot#706]
Currently the GCS failsafe will trigger an RTL if the user is flying using the virtual sticks.  Theoretically if the user is only using guided mode they might not be using the virtual sticks so the RTL would not trigger.
In practice this may not be a problem because the GCS might be overriding the rc controls even while in guided mode because it needs to raise the throttle above zero.

**Comment by R-Lefebvre** [comment]
This is fixed with this commit.

R-Lefebvre@8360b3d

Need commentary on if this will be satisfactory for cases where Guided mode is being used for a companion computer. I think it might work, as if the companion computer communication is lost, it will also RTL. The only problem there, is the master parameter is called "GCS_Failsafe", not "MAVlink Failsafe". Randy, you know this companion computer functionality better. Would this all be acceptable?

**Comment by rmackay9** [comment]
As discussed earlier today this looks good to me.
